Configuration:
  status: warn
  appenders:
    Console:
      name: STDOUT
      target: SYSTEM_OUT
      PatternLayout:
        Pattern: "%m%n"

  Loggers:
    logger:
      -
        name: com.wiley.realworldjava
        level: info
        additivity: false
        AppenderRef:
          ref: STDOUT
    Root:
      level: error
      AppenderRef:
        ref: STDOUT